// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TitleTrack.Api.Data;

#nullable disable

namespace TitleTrack.Api.Migrations
{
    [DbContext(typeof(TitleTrackDbContext))]
    [Migration("20260218213708_AddDocumentEntity")]
    partial class AddDocumentEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("TitleTrack.Api.Entities.AbstractReport", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountyID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SearchDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ReportID");

                    b.HasIndex("CountyID");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("PropertyAddress");

                    b.HasIndex("SearchDate");

                    b.ToTable("AbstractReports", (string)null);
                });

            modelBuilder.Entity("TitleTrack.Api.Entities.County", b =>
                {
                    b.Property<int>("CountyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CountyID");

                    b.HasIndex("Name", "State")
                        .IsUnique();

                    b.ToTable("Counties", (string)null);

                    b.HasData(
                        new
                        {
                            CountyID = 1,
                            Name = "Miami-Dade",
                            State = "FL"
                        },
                        new
                        {
                            CountyID = 2,
                            Name = "Broward",
                            State = "FL"
                        },
                        new
                        {
                            CountyID = 3,
                            Name = "Palm Beach",
                            State = "FL"
                        },
                        new
                        {
                            CountyID = 4,
                            Name = "Los Angeles",
                            State = "CA"
                        },
                        new
                        {
                            CountyID = 5,
                            Name = "Orange",
                            State = "CA"
                        });
                });

            modelBuilder.Entity("TitleTrack.Api.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AbstractReportId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Book")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Grantee")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Grantor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstrumentNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Page")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordingDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AbstractReportId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("TitleTrack.Api.Entities.AbstractReport", b =>
                {
                    b.HasOne("TitleTrack.Api.Entities.County", "County")
                        .WithMany("AbstractReports")
                        .HasForeignKey("CountyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("County");
                });

            modelBuilder.Entity("TitleTrack.Api.Entities.Document", b =>
                {
                    b.HasOne("TitleTrack.Api.Entities.AbstractReport", "AbstractReport")
                        .WithMany("Documents")
                        .HasForeignKey("AbstractReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AbstractReport");
                });

            modelBuilder.Entity("TitleTrack.Api.Entities.AbstractReport", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("TitleTrack.Api.Entities.County", b =>
                {
                    b.Navigation("AbstractReports");
                });
#pragma warning restore 612, 618
        }
    }
}
